### ISSUE TITLE
Build error - configure: error: pam_modules.h not found

### ISSUE THREAD

**Issue by jfcgaspar** [FreeRADIUS/pam_radius#103]
Hi,

So attempting to build pam_radius-3.0.0 and I am getting the following error on the **./configure** step

`checking for pam/pam_modules.h... no
configure: error: pam_modules.h not found`

I have attached the configure log. Am I missing some dependency ?

[configure.log](https://github.com/user-attachments/files/17524308/configure.log)

I have tried on RHEL 8.10 and Debian 12, both have returned with same error.

Thanks for any assitance

**Comment by alandekok** [comment]
You have to install the PAM header files.  These are part of some PAM developer package, and aren't included with the module.

**Comment by jfcgaspar** [comment]
Thanks, build was sucessful after installing **pam-devel** package.
