### ISSUE TITLE
PW_AUTHENTICATE_ONLY needed?

### ISSUE THREAD

**Issue by joakim-tjernlund** [FreeRADIUS/pam_radius#17]
We have a customer who claim that sending attribute Authenticate_Only make their
Radius server(Steel Belted Radius) skip sending back any attributes at all and the
code has this comment too:
/* not all servers understand this service type, but some do */
add_int_attribute(request, PW_USER_SERVICE_TYPE, PW_AUTHENTICATE_ONLY);

Should PW_AUTHENTICATE_ONLY really be used here?
If removed, could other Radius servers out there start to malfunction?

**Comment by alandekok** [comment]
The PAM module doesn't require any attributes in the Access-Accept.  Why is this a problem?

**Comment by joakim-tjernlund** [comment]
We have an extension that uses attributes from the server, we get the users priv. level that
way(admin, readonly etc.)

**Comment by alandekok** [comment]
If you have an extension, you can edit the source to get rid of that Service-Type.

**Comment by joakim-tjernlund** [comment]
I can and I will consider this. I would like to understand why it is there though. If the server sends some
attributes, these will be ignored anyway(FreeRadius will send attributes regardless) . I am unsure if something else could break if this setting was removed, you have any idea?

**Comment by alandekok** [comment]
It''s there because it's supposed to be there.  The PAM module is only asking for authentication.  It's not asking for any authorization.

It shouldn't break anything, but many RADIUS implementations are broken.  Test it and see.
