### ISSUE TITLE
pam_radius - Account lockouts

### ISSUE THREAD

**Issue by sarlacpit** [FreeRADIUS/pam_radius#21]
I have pam_radius working very well and it is great. 

I have a feature request, Freeradius doesn't seem to support account lock outs.
Is there a way for it to lock accounts after a number of failed attempts configured by the user. 
I am not sure if we able to use the pam_tally2 module in conjunction with it. I have tried but it just seems to mess up my logins. 

Thanks

**Comment by arr2036** [comment]
Hm, that's something that'd be implemented on the RADIUS server, and you can most certainly do that with your own policies today.

There's enough flexibility in unlang and the SQL module to implement counters.

**Comment by alandekok** [comment]
I agree.  This doesn't belong in the PAM RADIUS module.
