### ISSUE TITLE
Honor Prompt attribute during challenge-response

### ISSUE THREAD

**Issue by scootersmk** [FreeRADIUS/pam_radius#22]
Wanted to resurrect this issue that I found, which I had no involvement with at the time, and see if the project would be open to this enhancement if I coded it up and submitted it. There is reference to a bug that I assume is an old/retired bug tracking system, so I don't know where this effort ended back then. Long shot, but anyone know/remember why this enhancement died?

http://lists.freeradius.org/pipermail/freeradius-users/2008-October/032543.html
http://lists.freeradius.org/pipermail/freeradius-users/2008-October/032762.html
http://bugs.freeradius.org/show_bug.cgi?id=609

**Comment by alandekok** [comment]
It probably got lost in the shuffle.  It would be good to re-do the patch, as it may not apply cleanly to the code.

**Comment by alandekok** [comment]
This should now be fixed in the recent version.
