### ISSUE TITLE
Continuation of the  https://github.com/FreeRADIUS/pam_radius/issues/29

### ISSUE THREAD

**Issue by adireddi77** [FreeRADIUS/pam_radius#30]
With the master branch I am still seeing this issue where even valid users are not successfully authenticated. Does not seem that the credentials are being even sent. Code seems to hitting the FD size --

java: pam_radius_auth: Got user name xxxxxxxx
java: pam_radius_auth: Unusable socket, FD is larger than 1024
java: pam_radius_auth: Unusable socket, FD is larger than 1024

Is there any way to overcome this issue ?

**Comment by adireddi77** [comment]
Would using POLL help ?

**Comment by alandekok** [comment]
Using poll will help.  Or, using PAM in an application that opens less than 1K files.
