### ISSUE TITLE
Compiling Issues on Solaris 10

### ISSUE THREAD

**Issue by picabotwo** [FreeRADIUS/pam_radius#35]
Has anyone got this to work on Solaris 10? When I run ./configure the last few lines read.

checking pam/pam_appl.h presence no
checking for pam/security/pam_modules.h ...no

all those files are located in /usr/include/security

Thanks!

**Comment by alandekok** [comment]
Check you're using the latest revision from github.

**Comment by picabotwo** [comment]
I was able to finally compile it. It worked when Installed git and compiled it from that. I followed the instructions for Solaris 2.6 and edited the pam.conf and added the required lines. I am not sure if I need to edit anything to get it enabled for SSH.  I have it working fine on Centos 7 where it prompts for Two factor pin from a Radius server.  I am not sure if I am missing any step for Solaris 10. Thanks

**Comment by picabotwo** [comment]
Finally got it configured for Solaris 10. I am pretty sure I am pam.conf configured correctly. When I am looking at the pam log I am seeing errors such as:  pam_radius_auth: error sending RADIUS packet to server xxx.xxx.xxx.xxx: invalid arguement. Any ideas? Thanks! Josh

**Comment by alandekok** [comment]
I don't have Solaris and can't help, sorry.  It works on all other operating systems.
