### ISSUE TITLE
Only supports authentication, does not support billing/accounting?

### ISSUE THREAD

**Issue by tangxininjava** [FreeRADIUS/pam_radius#44]
centos7 yum install dante1.4.2
vim /etc/pam.d/sockd
account sufficient /lib64/security/pam_radius_auth.so
auth sufficient /lib64/security/pam_radius_auth.so

vim /etc/raddb/server
#Server     Secret      Timeout
192.168.1.2     testing123    60

table nas
id	nasname	shortname	type	ports	secret	server	community	description
1	0.0.0.0/0	sockd	other	1812	testing123			RADIUS Client

table radcheck
id	username	attribute	op	value
2	mimi1	Cleartext-Password	:=	1234567

table radpostauth
id	username	pass	reply	authdate
11896	mimi1	1234567	Access-Accept	2019-10-01 21:42:05

table radacct
radacctid	acctsessionid	acctuniqueid	username	groupname	realm	nasipaddress	nasportid	nasporttype	acctstarttime	acctstoptime	acctsessiontime	acctauthentic	connectinfo_start	connectinfo_stop	acctinputoctets	acctoutputoctets	calledstationid	callingstationid	acctterminatecause	servicetype	framedprotocol	framedipaddress	acctstartdelay	acctstopdelay	xascendsessionsvrkey

I hope radacct has data, How should I configure sockd or freeradius? Or is there any other better way?

**Comment by alandekok** [comment]
the PAM module sends RADIUS accounting packets when the module is called for PAM accounting.  Which is pretty much only start / stop session.

PAM does not support bandwidth usage or anything else.
