### ISSUE TITLE
RHEL 8 Support for PAM Radius

### ISSUE THREAD

**Issue by atanikan** [FreeRADIUS/pam_radius#45]
Hi we are upgrading our system from RHEL 7 to RHEL 8. I was just wondering if PAM Radius would support RHEL 8 Systems

**Comment by alancarwile** [comment]
Used and tested thoroughly on Centos. Given them/Centos relationship,
should be a definite yes.

**Comment by cipherboy** [comment]
Hi @atanikan and @alancarwile,

The upstream package isn't the correct place to be having this discussion. This should really be happening on either [`devel@lists.fedoraproject.org`](https://lists.fedoraproject.org/archives/list/devel%40lists.fedoraproject.org/) or more appropriately, on Bugzilla. However, `pam_radius` has already been built by Jason Taylor (\o Hi @jmtaylor90) for EPEL8. See [rh-bz#1769810](https://bugzilla.redhat.com/show_bug.cgi?id=1769810) and [FEDORA-EPEL-2019-df6f4b0b53](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-df6f4b0b53).

Note that this package won't be included in RHEL and will remain available through EPEL only.

**Comment by atanikan** [comment]
Oh my bad, I'll close this, thanks for pointing to the right resources. Also, glad it's available of epel8.
