### ISSUE TITLE
template user

### ISSUE THREAD

**Issue by terminaldweller** [FreeRADIUS/pam_radius#55]
is there a way to use the same functionality as freebsd's pam_radius' "template_user"?
the template_user option allows a user to authenticate as a "generic" user with a predefined template using radius on systems where they don't have a local account.

**Comment by jpereira** [comment]
We don't support the `template_user` yet. patches are welcome. next time, please send the questions to `freeradius-users@lists.freeradius.org.`

**Comment by terminaldweller** [comment]
ok. thank you.
