### ISSUE TITLE
noisy debugs for getservbyname in pam_radius_auth.c

### ISSUE THREAD

**Issue by ssbertilson** [FreeRADIUS/pam_radius#6]
Seems to me that they're useless but very chatty in their current form.

I'm wondering if you'd consider patching it to:
1) delete the 3 getservbyname DPRINTs
2) make them silent unless getservbyname fails

I'd also want to change the message - to not print the pointer value (in decimal of all things) but instead announce that the lookup failed when that happens.

**Comment by alandekok** [comment]
This should now be fixed in the HEAD
