### ISSUE TITLE
rlm_pam

### ISSUE THREAD

**Issue by c60cb859** [FreeRADIUS/pam_radius#70]
Is this repo the same a rlm_pam?
https://networkradius.com/doc/current/raddb/mods-available/pam.html

the documentation mentions mem leaks, but I find it very difficult to figure out what is what regarding PAM module for Radius

**Comment by alandekok** [comment]
The PAM RADIUS module gets passwords from PAM, and sends RADIUS packets to a RADIUS server.

The FreeRADIUS rlm_pam module gets passwords from RADIUS, and verifies them via PAM.

They are very different, and all of the documentation makes this clear.
