### ISSUE TITLE
PAM Radius + OVPN

### ISSUE THREAD

**Issue by Comandante1977** [FreeRADIUS/pam_radius#73]
Situation: I have fully configured and working Freeradius server. Installed OVPN 2.6.4 on other server. And goal is auth through Radius. Installed pam-radius-auth. Configured (confs below). Authentication is working just fine, but there are no Accounting packets from OVPN. When I'm trying pamtester - everyting is ok, accounting is here, but when I connected OVPN - no.

/etc/pam.d/ovpn

account required      pam_radius_auth.so
auth    required      pam_radius_auth.so conf=/etc/pam.d/pam_radius_auth.conf debug
session required      pam_radius_auth.so

/etc/pam.d/pam_radius_auth.conf

<My Radius server ip>  <Shared secret>       3

/etc/openvpn/server/server.conf

setenv deferred_auth_pam 1
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so ovpn
verify-client-cert none
key-direction 0
local *<IPaddr>*
port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA256
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
server-ipv6 fddd:1194:1194:1194::/64
push "redirect-gateway def1 ipv6 bypass-dhcp"
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 67.207.67.3"
push "dhcp-option DNS 67.207.67.2"
push "block-outside-dns"
push "explicit-exit-notify 3"
keepalive 10 120
cipher AES-128-GCM
user nobody
group nogroup
persist-key
persist-tun
verb 3
crl-verify crl.pem
explicit-exit-notify 1
management 127.0.0.1 7555
log-append /var/log/openvpn/openvpn.log
txqueuelen 4000
mute-replay-warnings

What I missing?

**Comment by jpereira** [comment]
@Comandante1977 You're complaining about the "OpenVPN". so, please ask the OpenVPN people about that.
